### ISSUE TITLE
Mainnet BTSCore Upgrade failed with message: ran out of gas

### ISSUE THREAD

**Issue by manishbista28** [icon-project/icon-bridge#469]
## Overview
BTSCore Upgrade done from main branch's [commit](https://github.com/icon-project/icon-bridge/commit/fecfacde13004ec3a1b20890680a868c012672fc) failed with error `"BTSCoreV2" ran out of gas. Something in the constructor (ex: infinite loop) caused gas estimation to fail.` when done on BSC Mainnet. New Implementation contract got created but the upgrade failed before this newly deployed implementation contract got linked with existing proxy contract.

Though the issue replicates when insufficient balance is used for the procedure, the exact cause of the error is still uncertain because the deployer account had sufficient balance to complete the upgrade (i.e. link proxy contract with new implementation contract).

## Steps to Reproduce
The issue can has be exactly replicated yet. An error same as the one thrown during the procedure can, however, be repeated if an insufficient balance is used.
1. Use insufficient balance
2. Run Upgrade and check error message

## Expected Behavior
Contract Upgrade should complete

## Additional Context
Error Message:
`
"BTSCoreV2" ran out of gas. Something in the constructor (ex: infinite loop) caused gas estimation to fail. Try:
   * Making your contract constructor more efficient
   * Setting the gas manually in your config or as a deployment parameter
   * Using the solc optimizer settings in 'truffle-config.js'
   * Setting a higher network block limit if you are on a
     private network or test client (like ganache).
`
    at /Users/johndoe/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:379:1
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at deploy (/Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/@openzeppelin/truffle-upgrades/src/utils/deploy.ts:9:48)
    at /Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/@openzeppelin/truffle-upgrades/src/utils/deploy-impl.ts:100:47
    at resumeOrDeploy (/Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/@openzeppelin/upgrades-core/src/deployment.ts:67:24)
    at /Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:54:23
    at Manifest.lockedRun (/Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/@openzeppelin/upgrades-core/src/manifest.ts:176:14)
    at fetchOrDeployGeneric (/Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:43:24)
    at fetchOrDeploy (/Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:108:11)
    at deployImpl (/Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/@openzeppelin/truffle-upgrades/src/utils/deploy-impl.ts:87:16)
    at upgradeProxy (/Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/@openzeppelin/truffle-upgrades/src/upgrade-proxy.ts:27:30)
    at module.exports (/Users/johndoe/dev/icon-bridge-deployment/icon-bridge-mainnet/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/migrations/4_upgrade_btsCore.js:9:26)
    at Migration._deploy (/Users/johndoe/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:72:1)
    at Migration._load (/Users/johndoe/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
    at Migration.run (/Users/johndoe/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/Users/johndoe/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
    at Object.runFrom (/Users/johndoe/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
    at runMigrations (/Users/johndoe/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:73:1)
    at Object.module.exports [as run] (/Users/johndoe/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
    at Command.run (/Users/johndoe/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)
Truffle v5.5.5 (core: 5.5.5)
Node v14.17.0
`

**Comment by pragyanshrestha-ibriz** [comment]
Findings:
1. Initial assumption on insufficient balance causing the issue may not answer the problem faced
2. what steps the upgrade failed and check if the deployer's account have sufficient amount to complete the upgrade
3. what can be the alternatives to completing the remaining upgrade: a) rerunning from scratch OR b) manually executing the remaining method OR c) checking truffle's source code to understand the issue and resuming the upgrade from there
 
No issues faced during testnet deployment. Exact case on the mainnet is not yet replicated yet.

**Comment by manishbista28** [comment]
The issue was that the upgrade did not proceed beyond a point. Implementation contract was deployed but this new contract could not get bound to the proxy contract.
we fixed it by manually changing the truffle code such that the upgrade would resume from the point in which the upgrade had halted. To be specific the file /node_modules/@openzeppelin/truffle-upgrades/dist/utils/deploy.js

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deploy = void 0;
async function deploy(deployer, contract, ...args) {
    /*const { address, transactionHash: txHash } = await deployer.deploy(contract, ...args);
    console.log("Trigger ", address, " and ", txHash);
    throw new Error('trigger manual');
    if (txHash === undefined) {
        throw new Error('Transaction hash is undefined');
    }*/
    return { address:"0x8AC0dB08f29b528b84ffa04371F585A0E06Cf9fC", txHash:"0xa4f82fe005e54db6759a88a584fd67e5bb080dcce7f72296c87bb548cd3c60d3" };
}
exports.deploy = deploy;
//# sourceMappingURL=deploy.js.map
```

The address and txHash values are obtained from [contract Creator](https://bscscan.com/address/0xcab1aabae9239f218a6fa6bc4428604d8ca22ac7)'s [transaction](https://bscscan.com/tx/0xa4f82fe005e54db6759a88a584fd67e5bb080dcce7f72296c87bb548cd3c60d3) 

Once the change was made and upgrade script was run,[ Upgrade method](https://bscscan.com/tx/0x4c7028f47ffce875af9aece4f9ce6e59e74133f1752f3c5e07a5376b02d7465e) got called to bind the new implementation contract.

Afterwards, we reverted the changed js code.

**Comment by manishbista28** [comment]
@sdpisreddevil @izyak 
could you please perform any other checks, if necessary, to verify the upgrade either remotely or through the deployment setup ?
