### ISSUE TITLE
Can't deploy contracts reason: 'ExistCoin'

### ISSUE THREAD

**Issue by andrii-kl** [icon-project/icon-bridge#826]
## Overview
I Can't deploy contracts reason: 'ExistCoin'

## Steps to Reproduce
1. Use config devnet/docker/icon-bsc/scripts/config/icon-ice-arctic-config.sh
2.  /bin/bash /icon-bridge/devnet/docker/icon-bsc/scripts/deploysc.sh
3. See error

**Comment by andrii-kl** [comment]
BSC_RPC_URI: https://arctic-rpc.icenetwork.io:9933
Using network 'bsc'.

ProviderError: VM Exception while processing transaction: revert ExistCoin -- Reason given: ExistCoin.
    at module.exports (/Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/scripts/bts.js:12:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: -32603,
  data: '0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000094578697374436f696e0000000000000000000000000000000000000000000000',
  reason: 'ExistCoin',
  hijackedStack: 'ProviderError: VM Exception while processing transaction: revert ExistCoin -- Reason given: ExistCoin.\n' +
    '    at /Users/anymac/.nvm/versions/node/v18.5.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:80:1\n' +
    '    at /Users/anymac/.nvm/versions/node/v18.5.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:118:1\n' +
    '    at /Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/web3-provider-engine/index.js:232:9\n' +
    '    at /Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/async/internal/once.js:12:16\n' +
    '    at replenish (/Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/async/internal/eachOfLimit.js:61:25)\n' +
    '    at /Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/async/internal/eachOfLimit.js:71:9\n' +
    '    at eachLimit (/Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/async/eachLimit.js:43:36)\n' +
    '    at /Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/async/internal/doLimit.js:9:16\n' +
    '    at end (/Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/web3-provider-engine/index.js:211:5)\n' +
    '    at Request._callback (/Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/web3-provider-engine/subproviders/rpc.js:70:28)\n' +
    '    at Request.self.callback (/Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/request/request.js:185:22)\n' +
    '    at Request.emit (node:events:537:28)\n' +
    '    at Request.<anonymous> (/Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/request/request.js:1154:10)\n' +
    '    at Request.emit (node:events:537:28)\n' +
    '    at IncomingMessage.<anonymous> (/Users/anymac/projects/web3j/icon-bridge/devnet/docker/icon-bsc/build/contracts/solidity/bts/node_modules/request/request.js:1076:12)\n' +
    '    at Object.onceWrapper (node:events:651:28)\n' +
    '    at IncomingMessage.emit (node:events:549:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1359:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
